name: Deploy

on:
  workflow_run:
    workflows: ["Delivery"]
    types:
      - completed
  workflow_dispatch:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Check if DEPLOY_SERVICE_NAME exists
        id: check_service_name
        run: |
          if [ -z "${{ vars.DEPLOY_SERVICE_NAME }}" ]; then
            echo "DEPLOY_SERVICE_NAME is empty, setting to empty string"
            echo "service_name=" >> $GITHUB_ENV
          else
            echo "DEPLOY_SERVICE_NAME is set to ${{ vars.DEPLOY_SERVICE_NAME }}"
            echo "service_name=${{ vars.DEPLOY_SERVICE_NAME }}" >> $GITHUB_ENV
          fi
      - name: Deploy Service
        run: |
          curl -i -X PATCH -H "Authorization:${{secrets.DEPLOY_TOKEN}}" "${{ vars.DEPLOY_URL }}/${{ env.service_name }}?wait_result=true"